import { promises as fs } from "node:fs";
import path from "node:path";
import { NextResponse } from "next/server";

// Dev-only endpoint: writes the edited CV back into source. Content (the CV
// object) replaces the block between the CV-DATA-START / CV-DATA-END sentinels
// in src/data/cv.ts; the design config (when sent) overwrites
// src/data/cv-config.ts so the /cv/edit dials carry over to the public page.
// Used by the lab's "Save to cv.ts" button. Never available in production.

export const runtime = "nodejs";

const START = "// === CV-DATA-START";
const END = "// === CV-DATA-END ===";

export async function POST(req: Request) {
  if (process.env.NODE_ENV === "production") {
    return new NextResponse("Not found", { status: 404 });
  }

  let body: { data?: unknown; config?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ ok: false, error: "invalid JSON" }, { status: 400 });
  }

  // Back-compat: an older client may POST the bare CV object (no { data } wrapper).
  const data =
    body && typeof body === "object" && "data" in body ? body.data : body;
  const config =
    body && typeof body === "object" && "config" in body ? body.config : undefined;

  const file = path.join(process.cwd(), "src", "data", "cv.ts");
  let src: string;
  try {
    src = await fs.readFile(file, "utf8");
  } catch {
    return NextResponse.json({ ok: false, error: "cv.ts not found" }, { status: 500 });
  }

  const startIdx = src.indexOf(START);
  const endIdx = src.indexOf(END);
  if (startIdx === -1 || endIdx === -1) {
    return NextResponse.json(
      { ok: false, error: "sentinels missing in cv.ts" },
      { status: 500 },
    );
  }

  const before = src.slice(0, startIdx);
  const after = src.slice(endIdx + END.length);
  const literal =
    `${START} (the block below is regenerated when you click\n` +
    `// "Save to cv.ts" in /cv/edit — keep these sentinel comments intact) ===\n` +
    `export const CV: CVData = ${JSON.stringify(data, null, 2)};\n` +
    `${END}`;

  try {
    await fs.writeFile(file, before + literal + after, "utf8");

    if (config && typeof config === "object") {
      const configFile = path.join(process.cwd(), "src", "data", "cv-config.ts");
      const configLiteral =
        `import type { CVDocConfig } from "@/components/cv/cv-document";\n\n` +
        `// Published /cv design. Regenerated by the /cv/edit "Save to cv.ts" button, so\n` +
        `// the dials you set in the lab carry over to the public, read-only page + PDF.\n` +
        `export const PUBLISHED_CONFIG: CVDocConfig = ${JSON.stringify(config, null, 2)};\n`;
      await fs.writeFile(configFile, configLiteral, "utf8");
    }
  } catch {
    return NextResponse.json({ ok: false, error: "write failed" }, { status: 500 });
  }

  return NextResponse.json({ ok: true });
}
