import type { CVDocConfig } from "@/components/cv/cv-document";

// Published /cv design. Regenerated by the /cv/edit "Save to cv.ts" button, so
// the dials you set in the lab carry over to the public, read-only page + PDF.
export const PUBLISHED_CONFIG: CVDocConfig = {
  "headerDir": 1,
  "techStyle": 1,
  "linkStyle": 1,
  "emblem": "none",
  "sidebarStyle": "card",
  "colSplit": 0.6,
  "headerScale": 1,
  "headerPad": 1.49,
  "textScale": 0.97,
  "lineScale": 1
};
