import type { CVDocConfig } from '@/components/cv/cv-document';

// Published /cv design. Regenerated by the /cv/edit "Save to cv.ts" button, so
// the dials you set in the lab carry over to the public, read-only page + PDF.
export const PUBLISHED_CONFIG: CVDocConfig = {
  techStyle: 1,
  linkStyle: 1,
  emblem: 'rings',
  sidebarStyle: 'card',
  colSplit: 0.6,
  headerScale: 1.6,
  headerPad: 0.8,
  textScale: 0.92,
  lineScale: 1
};

